name: build
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
  security-events: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Build an image from Dockerfile
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "docker.io/my-organization/my-app:$IMAGE_TAG" .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@d2a0b60797ff03db6132bd4e2b293f9b37081297 # master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@f3712979fa5f215279b101dd0a2e3bdfb4353324 # v3
        with:
          sarif_file: 'trivy-results.sarif'
